### ISSUE TITLE
com.astuetz.viewpager.extensions.PagerSlidingTabStrip

### ISSUE THREAD

**Issue by akex31** [balaji-k13/Navigation-drawer-page-sliding-tab-strip#3]
HI, your libray seems great.
I try to use it without success.

In the xml file, fragment_quick_contact, <com.astuetz.viewpager.extensions.PagerSlidingTabStrip is unknow and so i have an xml error.
I try to change it to com.astuetz.PagerSlidingTabStrip but then the app lauch but crashes.

Is there something i'm missing ?

Thanks.

**Comment by kfaizullabhoy** [comment]
Few things need to be done as the namespace in the :PagerSlidingTabStrip was updated but this project was not updated
1. Fragmentparent needs to be updated to com.astuetz.PagerSlidingTabStrip instead of com.astuetz.viewpager.extensions.PagerSlidingTabStrip
2. In fragment_quick_contact we need to add psts to each of the following as below

app:pstsDividerColor="#00000000"
        app:pstsIndicatorColor="#FF33B5E6"
        app:pstsTabPaddingLeftRight="14dip"
        app:pstsUnderlineColor="#FF33B5E6"
1. pager needs to be updated to com.astuetz.PagerSlidingTabStrip instead of com.astuetz.viewpager.extensions.PagerSlidingTabStrip

This will ensure the app doesn't crash...;)

**Comment by balaji-k13** [comment]
I have done changes to support PagerSlidingTabStrip TAG 1.0.1
